### ISSUE TITLE
gRPC client example is not clear very much.

### ISSUE THREAD

**Issue by pathbox** [bigcommerce/gruf-demo#1]
Hi~
  I try the gRPC in rails with gruf, and I had a hard time at first, because the example is not clear very much. Then I find `gruf-demo`, I get the grpc server example, but I didn't find the client example. At last I find the rake script, I read the code and understand how to do, and I make it. This is my code in github: https://github.com/pathbox/Rails_Communicate_Rails. 
  I just suggest that you can try to add the grpc client example

**Comment by splittingred** [comment]
Closing this, as docs are in https://github.com/bigcommerce/gruf/wiki
